twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        phone_number: '%env(PHONE_NUMBER)%'
        google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
when@test:
    twig:
        strict_variables: true
