controllers:
    requirements:
        _locale: en|fr
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
root:
    path: /
    controller: App\Controller\Public\HomeController::index
    defaults:
        _locale: fr
